name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.9
      - name: Pyodide-build
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.14
      - run: pip install pyodide-build
      - run: make wheel
      - name: Upload wheel to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: biopython-pyodide.whl
          asset_name: biopython-pyodide.whl
          overwrite: true
          body: "Upload to GitHub"
          tag: ${{ github.ref }}
          
    
